### PR TITLE
♻️ Overhaul Android permissions docs

### LINKED ISSUE #464: 🛂 Android permissions tweak to allow app to use location
Follow-up to #379

While looking into getditto/ditto#7602, removing these `android:maxSdkVersion` is not sufficient to allow an app to continue requesting location permission on Android 13. Our SDK actually includes these permissions with that attribute and when our library's manifest is merged with the app's manifest, these attributes will come back.

If the app needs to use location on Android 13 they need to specifically override the permissions coming from our library like so:

```xml
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"
        tools:remove="android:maxSdkVersion" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"
        tools:remove="android:maxSdkVersion" />
```

The `tools:remove="android:maxSdkVersion"` attribute says "remove the `android:maxSdkVersion` attribute when merging manifests ".

Note that this `tools:remove` attribute may show as an error. If that happens, add `xmlns:tools="http://schemas.android.com/tools"` to the root `<manifest>` element.

_Originally posted by @phatblat in https://github.com/getditto/docs/issues/379#issuecomment-1434951573_

### PR DESCRIPTION
**Pull request by phatblat**
Fixes #464

The root cause behind getditto/ditto#7602 revealed that _it mostly doesn't matter what permissions an app configures in their `AndroidManifest.xml`_. This is because the Android build process automatically adds the permissions that are included in our Android SDK library's [`AndroidManifest.xml`](https://github.com/getditto/ditto/blob/main/android/ditto/src/main/AndroidManifest.xml). They can certainly add these permissions if they want and this is required if they are going to **override** the permissions coming from our library.

This was the case with one customer that needed location permissions all the time. I've revised our Android permission docs to remove the legacy permissions because the API-bounded permissions are suitable for any OS version we support.

More importantly, I included an important example of how an app that needs location permission for their own functionality can configure their manifest and override the `maxSdkVersion` that we set the location permissions.

### CODE REVIEW

**Comment by phatblat** [comment]
@okdistribute Is it possible to include [`AndroidManifest.xml`](https://github.com/getditto/ditto/blob/main/android/ditto/src/main/AndroidManifest.xml) verbatim?

**Comment by okdistribute** [comment]
Not sure what you mean, I don't know android well enough to make the call on that. Or are you asking more generally about open sourcing the internal android manifest used in the monorepo? If the latter, it looks like it would be a good idea since it doesn't contain any privileged information.

**Comment by okdistribute** [comment]
@npb12 @phatblat if this fixed the issue for the customer, we can just merge-as is

**Review by okdistribute — APPROVED** [review]

**Comment by phatblat** [comment]
Yep, they confirmed that location is working again for them.

**Comment by abunur** [comment]
@phatblat does this require the developer to use the Ditto helper class for permissions management? Will that be an issue if they are using Compose and/or handling the permissions requests themselves? Or is this delta only dealing with the manifest structure itself and in no way affecting the permissions request piece in the developer's app?

**Comment by phatblat** [comment]
Using out permission helper isn't required. If the current helper doesn't work well for a Compose app we should either fix that or add another that plays nicer with Compose

The main purpose of this overhaul was to simplify down to a single example app manifest and add an example of overriding the attributes of the permissions that come from our library. See #7701 for some ideas how to streamline this going forward.

**Comment by abunur** [comment]
Sounds good!

**Pull request merged**
