### PR TITLE
Remove maxSdkVersion from Android permission doc

### PR DESCRIPTION
**Pull request by kndoshn**
Our demo app had an issue of missing permissions about locations on Android 13 (API Level 33).

I think we can remove the `maxSdkVersion` limit from our doc since the latest OS is still asking for this permission, and the users of our SDK will need to face the same issue when newer OS comes out.

### CODE REVIEW

**Comment by phatblat** [comment]
@kndoshn What do you mean by "latest OS is still asking for this permission"? 

The [`NEARBY_WIFI_DEVICES`](https://developer.android.com/guide/topics/connectivity/wifi-permissions) permission (added in Android 13, API 33) effectively replaces the need for requesting location permission. This is the reason that `ACCESS_FINE_LOCATION` is only requested up through API 32 (Android 12L). Removing the `maxSdkVersion="32"` from our docs won't change our Android SDK behavior which only requests `ACCESS_FINE_LOCATION` on Android 12L and lower.
https://github.com/getditto/ditto/blob/main/android/dittotransports/src/main/java/live/ditto/transports/DittoSyncPermissions.kt#L107

**Review by abunur — APPROVED** [review]
I think we also need to update the documentation corresponding to this:
https://github.com/getditto/docs/pull/379#issuecomment-1339724883

Someone can make a ticket, I'll also make a note to myself to make the update and submit a separate PR for it. @phatblat @okdistribute

**Comment by okdistribute** [comment]
@phatblat good point, however we saw permissions issues with the Android Inventory app which is why this came to light: https://github.com/getditto/demo-apps/commit/3376be6cec09ccfacf932433bb3c4c9634bca633

**Comment by phatblat** [comment]
Was making this change to the demo apps' `AndroidManifest.xml` enough to resolve the issue? Did you add code to request `ACCESS_FINE_LOCATION`? The SDK doesn't currently request that permission on Android 13.

**Comment by kndoshn** [comment]
@phatblat 

> Did you add code to request ACCESS_FINE_LOCATION?

Yes, the app is asking users permissions, not SDK. Sorry for the confusion:
https://github.com/getditto/demo-apps/blob/master/Inventory/Android/app/src/main/java/live/ditto/InventoryP2PTest/MainActivity.kt#L194

> Was making this change to the demo apps' AndroidManifest.xml enough to resolve the issue?

Yes - by removing the `maxSdkVersion` from the manifest, we don't see the error logs anymore. Do you know anything related to this?

***
@abunur
> Do we also need to update to the documentation to correspond to this change?

This PR is supposed to be changing the page, but let me know if I'm missing something.

**Comment by abunur** [comment]
@kndoshn I was referring to the text portion of the document, not the code portion, but upon further review it still seems to read correctly after the deletion. So I think we are good to go in that regard.

**Comment by phatblat** [comment]
While looking into getditto/ditto#7602, removing these `android:maxSdkVersion` is not sufficient to allow an app to continue requesting location permission on Android 13. Our SDK actually includes these permissions with that attribute and when our library's manifest is merged with the app's manifest, these attributes will come back.

If the app needs to use location on Android 13 they need to specifically override the permissions coming from our library like so:

```xml
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"
        tools:remove="android:maxSdkVersion" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"
        tools:remove="android:maxSdkVersion" />
```

The `tools:remove="android:maxSdkVersion"` attribute says "remove the `android:maxSdkVersion` attribute when merging manifests ".

Note that this `tools:remove` attribute may show as an error. If that happens, add `xmlns:tools="http://schemas.android.com/tools"` to the root `<manifest>` element.

**Pull request merged**
