### PR TITLE
OAuth & API Key Documentation for HTTP API

### PR DESCRIPTION
**Pull request by npb12**
In reference to this [issue](https://github.com/getditto/ditto/issues/6133), we've added documentation for working with OAuth and creating an API Key for the HTTP API

### CODE REVIEW

**Comment by okdistribute** [comment]
Nice thanks neil. I'm going to put this in `docs/http/security`

**Comment by okdistribute** [comment]
Ah you weren't at the tip of the docs `main` branch so this is a bit out of date and won't merge cleanly because we've had some big changes to the docs repo since you last called `git pull`. No worries though, I will create a new branch tomorrow and copy-paste it over there.

**Comment by npb12** [comment]
It's strange because I've clone the repo in a new directory but still seeing the older format. Must be missing something.

**Comment by okdistribute** [comment]
Hm are you on the master branch or main?

**Pull request closed without merging**
